export default {
    about_us:'À propos ',
    contact_details:'Détails du contact',
    email:'Email',
    phone:'Téléphone',
    login_page_title:'CONNEXION DU CONDUCTEUR',
    driver_account_approve_err:'Votre compte n\'est pas encore approuvé en tant que conducteur.',
    account_not_exsist:'Votre compte n\'existe pas en tant que chauffeur.',
    driver_ride_complete_status:' Le conducteur a terminé votre course. votre identifiant de réservation est',
    please_wait:'Calcul de votre tarif',
    on_trip:'En Course',
    complete_trip:'COMPLETE LA COURSE',
    account_successful_done:'Votre compte a été créé avec succès et en attente de confirmation d\'approbation par l\'administrateur.',
    image_size_error:'La taille de l\'image ne doit pas être supérieure à 2 Mo.',
    password_blank_error:'Le mot de passe ne peut pas être vide.',
    password_complexity_alphabet:'Le mot de passe doit comprendre au moins 1 caractère alphanumérique et une longueur de 8 à 15.',
    password_complexity_complex:'Le mot de passe doit contenir au moins 1 lettre majuscule, 1 lettre minuscule, 1 chiffre et 1 caractère spécial d\'une longueur de 6 à 10.',
    driver_registration:'Inscription du conducteur',
    first_name:'Prénom',
    first_name_error:'Entrez votre prénom s\'il vous plait',
    last_name:'Nom',
    last_name_error:'Entrez votre nom s\'il vous plaite',
    email_blank_error:'S\'il vous plaît, mettez une adresse email valide',
    mobile:'Numéro de téléphone',
    password:'Mot de passe',
    confrim_password:'Confirmez le mot de passe',
    password_not_match:'Le mot de passe ne correspond pas',
    vehicle_model_name:'Modèle de véhicule',
    vehicle_model_name_blank_error:'Le nom du véhicule ne peut pas être vide',
    vehicle_reg_no:'Numéro d\'immatriculation du véhicule',
    vehicle_number_blank_err:'Le numéro de véhicule ne peut pas être vide',
    upload_driving_lisence:'Téléchargez votre permis de conduire',
    image_size_warning:'(Taille de l\'image: 2 Mo maximum)',
    reg_no:'S\'inscrire ',
    update_profile:'Mettre à jour le profil',
    valid_mobile_number:'S\'il vous plaît entrer un numéro de téléphone portable valide',
    update_now:'Mettez à jour maintenant',
    no_notification:'Aucune notification trouvée',
    forgot_password:'Mot de passe oublié?',
    valid_email_err:'S\'il vous plaît, mettez une adresse email valide',
    send_email:'Envoyer un Email',
    enter_code:'Entrer le code',
    submit:'Soumettre',
    change_password:'Changer le mot de passe ?',
    old_password:'Ancien mot de passe',
    old_password_err:'Veuillez saisir un ancien mot de passe',
    new_password:'nouveau mot de passe',
    new_password_err:'Veuillez saisir un nouveau mot de passe',
    update:'Mettre à jour',
    login:'S\'identifier',
    booking_request:'Demandes de réservation',
    profile_settings:'Paramètres de profil',
    incomeText:"Mes gains",
    my_bookings:'Mes réservations',
    sign_out:'Se déconnecter',
    rider_ride_cancel_text:'Le client a annulé la course',
    mobile_no_found:'Numéro de téléphone introuvable',
    firebase_otp_error:'Erreur d\'authentification avec OTP mobile. Vérifiez votre numéro de portable. Vous devez ajouter l\'indicatif de pays  devant.',
    login_title:'Connexion avec numéro de téléphone',
    mobile_no_placeholder:'Numéro de portable',
    mobile_no_blank_error:'s\'il vous plaît entrer un numéro de téléphone valide.',
    otp_error:'Veuillez saisir le bon OTP',
    otp_here:'Veuillez entrer OTP ici',
    sending_otp:"Envoi d'OTP ...",
    authorize:'Autoriser',
    request_otp:"Demander OTP",
    driver_journey_err:'Le chauffeur a commencé votre course. Votre identifiant de réservation est',
    wait_for_rider:'ATTENDRE LE CLIENT',
    rider_notified:'Le client a été averti',
    start_trip:'DÉMARRER LA COURSE',
    cancel_reson_1:'Impossible de contacter le chauffeur',
    cancel_reson_2:'Le conducteur ne bouge pas dans ma direction',
    cancel_reson_3:'Ma raison n\'est pas répertoriée',
    cancel_reson_4:'Conducteur refusé la course',
    cancel_reson_5:'Conducteur n\'arrive pas à l\'heure prévue',
    api_error:'Erreur d\'API Google place',
    accept_booking_request:'Votre demande de réservation acceptée',
    pickup_location:'Point de Départ',
    drop_location:'Point d\'arrivée',
    ignore_text:'Ignorez',
    modal_close:'Modal a été fermé.',
    alert_text:'Alerte',
    ignore_job_title:'Voulez-vous ignorer ce travail?',
    cancel:'Annuler',
    ok:'OK',
    accept:'Acceptez',
    task_list:'Liste de tâches',
    rider_not_here:'Actuellement aucun client dans votre région',
     booking_request_rejected:'Votre demande de réservation a été rejetée par le chauffeur demandé',
    driver_requested_for_payment:'Le chauffeur a demandé le paiement. Votre identifiant de réservation est',
    driver_completed_ride:'Le chauffeur a terminé la course. Veuillez payer en espèces. Votre identifiant de réservation est',
    complete_ride:'COMPLETE LA COURSE',
    request_payment:'DEMANDE DE PAIEMENT',
    my_rides:'Mes courses',
    password_reset_link:'Un lien de réinitialisation du mot de passe envoyé à votre e-mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    notification:'Notifications',
    chat_blank:'s\'il vous plaît écrivez quelque chose ...',
    send_msg:',vous a envoyé un message: \n',
    driver:'Conducteur',
    chat_history_not_found:'Aucun historique de chat trouvé',
    chat:'Conversation',
    send:'Envoyer',
    type_messege:'Tapez votre message',
    photo_upload_action_sheet_title:'Choisissez un type de média ?',
    camera:'Caméra',
    galery:'Galerie',
    yes:'Oui',
    password_change:'Votre mot de passe a bien été mis à jour',
    confrim:'Confirmation',
    delete_account_question:'Voulez-vous supprimer votre compte ?',
    my_profile:'Mon profil',
    active_status:'Statut Actif',
    profile_details:'Détails du profil',
    location:'Emplacement',
    mobile_no:'Numéro de téléphoner',
    preffered_lang:'langue préférée',
    lang:'Français',
    delete_account:'Supprimer le compte',
    payment_info:'Informations de paiement du client',
    booking_details:'Détails de mes réservations',
    you_rate_text:'Vous avez été évalué',
    no_rated_text:'Vous n\'avez pas de note',
    bill_details:'Détails de la facture',
    your_trip:'Votre Course',
    total_bill:'Facture totale',
    include_tax:'Toutes taxes comprises',
    total_payable:'Ma commission',
    go_to_booking:'Aller à la réservation',
    my_booking:'Mes réservations',
    job_ignore:'Voulez-vous ignorer ce travail?',
    show_modal:'Afficher le modal',
    notification_title:'Notification Zomuje',
    register:'S\'inscrire',
    today:'Gains d\'aujourd\'hui',
    thismonth:'Gains de ce mois-ci',
    totalearning:'Gain total',
    convenienceFee:'Frais de commodité',
    paymentStatus:'Statut de paiement',
    payment_mode:'Mode de paiement',
    customer_payable:'Payable Par le Client',
    discount_amount:'Montant de la remise',
    CardPaymentAmount:'Payer par carte -',
    CashPaymentAmount:'Payer en espèce -',
    WalletPayment:'Payer par portefeuille -',
    android_channel: 'Notifications Zomuje',
    terms:"Termes et conditions",
    email_login:'Connexion avec Email',
    register_email:'Inscrivez-vous par Email',
    ok:'OK',
    spacer_message:'OU CONNECTEZ-VOUS AVEC',
    password_blank_messege:'Le mot de passe ne peut pas être vide.',
    confrim_password_placeholder:'Confirmez le mot de passe',
    confrim_password_not_match_err:'Le mot de passe et la confirmation du mot de passe ne correspondent pas',
    valid_email_check:'S\'il vous plaît, mettez une adresse email valide.',
    forgot_password_link:"Mot de passe oublié ou réinitialisé?",
    forgot_password_confirm:"Êtes-vous sûr de vouloir réinitialiser le mot de passe?",
    forgot_password_success_messege:'Un lien de réinitialisation du mot de passe envoyé à votre e-mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    email_not_found:'E-mail introuvable dans la base de données',
    password_alphaNumeric_check:'Le mot de passe doit comprendre au moins 1 caractères alphanumériques et une longueur de 8 à 15.',
    password_complexity_check:'Le mot de passe doit contenir au moins 1 lettre minuscule, 1 lettre majuscule, 1 chiffre, 1 caractère spécial et une longueur de 6 à 10.',
    email_placeholder :"Email",
    password_placeholder:"Mot de passe",
    login_button:"S'identifier",
    register_link:"S'inscrire",
    car_type:'Type de voiture',
    upload_image_error: 'Problème d\'image téléversée. Veuillez réessayer.',
    select_country:'Choisissez le pays',
    country_blank_error:'Veuillez sélectionner le pays',
    email_verify_message:'Veuillez vérifier votre adresse e-mail. L\'e-mail est déjà envoyé dans votre boîte de réception.',
    downloading_updates: 'Téléchargement des mises à jour...',
    checking_updates: 'Recherche de mises à jour ...',
    fetching_data: 'Récupération des données...',
    loading_assets:'Chargement des actifs ...'
}